SignalConfigs:
  - SigId: "0x0"
    Category: "0x1"
    Name: INSTALL
    Enable: true
    TargetsEnabled: ["sun", "moon"]
    Permissions: ["system", "third_party"]
    Derivatives: ["solar"]
    Timeout: 4000
    Resources:
      - {ResId: "0x0", ResType: "0x1", OpInfo: 0, Values: [700]}

  - SigId: "0x1"
    Category: "0x1"
    Name: EARLY_WAKEUP
    Enable: true
    TargetsDisabled: ["sun"]
    Permissions: ["system"]
    Derivatives: ["solar"]
    Timeout: 5000
    Resources:
      - {ResId: "0", ResType: "1", OpInfo: 0, Values: [300, 400]}
      - {ResId: "1", ResType: "1", OpInfo: 1024, Values: [12, 45]}
      - {ResId: "2", ResType: "1", OpInfo: 32, Values: [5]}
      - {ResId: "3", ResType: "1", OpInfo: 256, Values: [23, 90]}
      - {ResId: "4", ResType: "1", OpInfo: 512, Values: [87]}
