TargetConfig:
  - TargetName: qli
    ClusterInfo:
      - Id: 0
        Type: big
      - Id: 1
        Type: little
      - Id: 2
        Type: prime
      - Id: 3
        Type: titanium
    ClusterSpread:
      - Id: 0
        NumCores: 4
      - Id: 1
        NumCores: 4
      - Id: 2
        NumCores: 4
      - Id: 3
        NumCores: 4
    TotalCoreCount: 16
