var searchData=
[
  ['cache_20info_20config_0',['Fields Description for Cache Info Config',['../index.html#autotoc_md37',1,'']]],
  ['cacheinfo_1',['CacheInfo',['../structCacheInfo.html',1,'']]],
  ['callbacks_2',['2. Applier and Teardown Callbacks',['../extensions.html#autotoc_md125',1,'']]],
  ['capabilities_3',['2. Defining feature init, relay and teardown capabilities',['../ext_features.html#autotoc_md130',1,'']]],
  ['capacity_20for_20efficiency_4',['11. Pre-Allocate Capacity for efficiency',['../index.html#autotoc_md98',1,'']]],
  ['cgroup_20config_5',['cgroup config',['../index.html#autotoc_md35',1,'Fields Description for CGroup Config'],['../usage.html#autotoc_md115',1,'Sample Cgroup config']]],
  ['cgroupconfiginfo_6',['CGroupConfigInfo',['../structCGroupConfigInfo.html',1,'']]],
  ['cgroups_20map_7',['2. Cgroups map',['../index.html#autotoc_md33',1,'']]],
  ['checking_8',['6. Duplicate Checking',['../index.html#autotoc_md93',1,'']]],
  ['cleanup_9',['4. Pulse Monitor: Detection of Dead Clients and Subsequent Cleanup',['../index.html#autotoc_md91',1,'']]],
  ['cli_10',['Client CLI',['../index.html#autotoc_md100',1,'']]],
  ['client_20apis_11',['Client APIs',['../group__RESOURCE__TUNER__CLIENT__APIS.html',1,'']]],
  ['client_20cli_12',['Client CLI',['../index.html#autotoc_md100',1,'']]],
  ['client_20garbage_20collector_13',['Client Garbage Collector',['../group__CLIENT__GARBAGE__COLLECTOR.html',1,'']]],
  ['client_20level_20permissions_14',['1. Client-Level Permissions',['../index.html#autotoc_md88',1,'']]],
  ['clientdatamanager_15',['ClientDataManager',['../classClientDataManager.html',1,'']]],
  ['clientendpoint_16',['ClientEndpoint',['../classClientEndpoint.html',1,'']]],
  ['clientexists_17',['clientExists',['../classClientDataManager.html#abdaa9fb64a8ff9cbebfbeeb34bab2ac4',1,'ClientDataManager']]],
  ['clientgarbagecollector_18',['ClientGarbageCollector',['../classClientGarbageCollector.html',1,'']]],
  ['clientgarbagecollector_2eh_19',['ClientGarbageCollector.h',['../ClientGarbageCollector_8h.html',1,'']]],
  ['clients_20and_20subsequent_20cleanup_20',['4. Pulse Monitor: Detection of Dead Clients and Subsequent Cleanup',['../index.html#autotoc_md91',1,'']]],
  ['cluster_20map_21',['1. Logical Cluster Map',['../index.html#autotoc_md32',1,'']]],
  ['clusterinfo_22',['ClusterInfo',['../structClusterInfo.html',1,'']]],
  ['cocotable_23',['cocotable',['../classCocoTable.html',1,'CocoTable'],['../group__COCO__TABLE.html',1,'Concurrency Coordinator Table (CocoTable)']]],
  ['cocotable_2eh_24',['CocoTable.h',['../CocoTable_8h.html',1,'']]],
  ['collector_25',['Client Garbage Collector',['../group__CLIENT__GARBAGE__COLLECTOR.html',1,'']]],
  ['common_20initialization_20configs_26',['Common Initialization Configs',['../index.html#autotoc_md29',1,'']]],
  ['common_20properties_20configs_27',['Common Properties Configs',['../index.html#autotoc_md48',1,'']]],
  ['common_20resource_20configs_28',['Common Resource Configs',['../index.html#autotoc_md41',1,'']]],
  ['componentregistry_29',['ComponentRegistry',['../classComponentRegistry.html',1,'']]],
  ['concurrency_20coordinator_20table_20cocotable_30',['Concurrency Coordinator Table (CocoTable)',['../group__COCO__TABLE.html',1,'']]],
  ['config_31',['config',['../index.html#autotoc_md47',1,'3. Properties Config'],['../index.html#autotoc_md37',1,'Fields Description for Cache Info Config'],['../index.html#autotoc_md35',1,'Fields Description for CGroup Config'],['../index.html#autotoc_md36',1,'Fields Description for Mpam Group Config'],['../usage.html#autotoc_md115',1,'Sample Cgroup config']]],
  ['config_20file_32',['config file',['../usage.html#autotoc_md118',1,'Sample Device Config file'],['../usage.html#autotoc_md121',1,'Sample Properties config file.']]],
  ['config_20file_20with_20two_20resources_33',['Sample Resource config file with two resources.',['../usage.html#autotoc_md109',1,'']]],
  ['config_20files_20format_34',['Config Files Format',['../index.html#autotoc_md27',1,'']]],
  ['configprocessor_35',['ConfigProcessor',['../classConfigProcessor.html',1,'']]],
  ['configs_36',['configs',['../index.html#autotoc_md28',1,'1. Initialization Configs'],['../index.html#autotoc_md40',1,'2. Resource Configs'],['../extensions.html#autotoc_md126',1,'3. Custom Configs'],['../usage.html#autotoc_md114',1,'3. How to add init configs'],['../index.html#autotoc_md53',1,'4. Signal Configs'],['../index.html#autotoc_md56',1,'5. (Optional) Target Configs'],['../index.html#autotoc_md59',1,'6. (Optional) ExtFeatures Configs'],['../index.html#autotoc_md29',1,'Common Initialization Configs'],['../index.html#autotoc_md48',1,'Common Properties Configs'],['../index.html#autotoc_md41',1,'Common Resource Configs'],['../index.html#autotoc_md30',1,'Overriding Initialization Configs'],['../index.html#autotoc_md49',1,'Overriding Properties Configs'],['../index.html#autotoc_md42',1,'Overriding Resource Configs']]],
  ['configtype_37',['ConfigType',['../Extensions_8h.html#ac254e872972d56fde0b2d9b767e157a9',1,'Extensions.h']]],
  ['configure_38',['configure',['../classLogger.html#adbf91c067f5ac2af04c8acbf80d11f31',1,'Logger']]],
  ['contact_39',['Contact',['../index.html#autotoc_md106',1,'']]],
  ['contents_40',['Table of Contents',['../index.html#autotoc_md1',1,'']]],
  ['coordinator_20table_20cocotable_41',['Concurrency Coordinator Table (CocoTable)',['../group__COCO__TABLE.html',1,'']]],
  ['cpu_20architecture_20details_42',['4. How to enforce CPU architecture details',['../usage.html#autotoc_md117',1,'']]],
  ['crash_20recovery_43',['9. Crash Recovery',['../index.html#autotoc_md96',1,'']]],
  ['create_20a_20resource_20opcode_20rescode_20and_20signal_20opcode_20sigcode_44',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md122',1,'']]],
  ['createnewclient_45',['createNewClient',['../classClientDataManager.html#a9dadece9ae9515cea2ae5a7fc20bd063',1,'ClientDataManager']]],
  ['createproperty_46',['createProperty',['../classPropertiesRegistry.html#ae0a22440795ed868651da51f8af43f85',1,'PropertiesRegistry']]],
  ['custom_20configs_47',['3. Custom Configs',['../extensions.html#autotoc_md126',1,'']]],
  ['custom_20extension_20file_48',['custom extension file',['../index.html#autotoc_md43',1,'Overiding with Custom Extension File'],['../index.html#autotoc_md31',1,'Overiding with Custom Extension File']]],
  ['custom_20properties_20file_49',['Overiding with Custom Properties File',['../index.html#autotoc_md50',1,'']]],
  ['custom_20resource_50',['1. How to add a custom resource',['../usage.html#autotoc_md108',1,'']]]
];
