var searchData=
[
  ['table_20cocotable_0',['Concurrency Coordinator Table (CocoTable)',['../group__COCO__TABLE.html',1,'']]],
  ['table_20of_20contents_1',['Table of Contents',['../index.html#autotoc_md1',1,'']]],
  ['table_20to_20get_20the_20value_20of_20restype_20for_20a_20resource_2',['List Of Resource Types (Use this table to get the value of ResType for a Resource)',['../index.html#autotoc_md65',1,'']]],
  ['target_20configs_3',['5. (Optional) Target Configs',['../index.html#autotoc_md56',1,'']]],
  ['targetregistry_4',['TargetRegistry',['../classTargetRegistry.html',1,'']]],
  ['targetregistry_2eh_5',['TargetRegistry.h',['../TargetRegistry_8h.html',1,'']]],
  ['teardown_20callbacks_6',['2. Applier and Teardown Callbacks',['../extensions.html#autotoc_md125',1,'']]],
  ['teardown_20capabilities_7',['2. Defining feature init, relay and teardown capabilities',['../ext_features.html#autotoc_md130',1,'']]],
  ['teardownfeatures_8',['teardownFeatures',['../classExtFeaturesRegistry.html#aa563b40b2c05933b18e64f4597ae251a',1,'ExtFeaturesRegistry']]],
  ['the_20extfeaturesconfig_20yaml_20be_20placed_9',['3. Where should the ExtFeaturesConfig.yaml be placed?',['../ext_features.html#autotoc_md132',1,'']]],
  ['the_20resource_20tune_20and_20untune_20functionalities_10',['2. How to override the Resource tune and untune functionalities.',['../usage.html#autotoc_md112',1,'']]],
  ['the_20value_20of_20restype_20for_20a_20resource_11',['List Of Resource Types (Use this table to get the value of ResType for a Resource)',['../index.html#autotoc_md65',1,'']]],
  ['this_20table_20to_20get_20the_20value_20of_20restype_20for_20a_20resource_12',['List Of Resource Types (Use this table to get the value of ResType for a Resource)',['../index.html#autotoc_md65',1,'']]],
  ['thread_20pool_13',['Thread Pool',['../group__THREAD__POOL.html',1,'']]],
  ['threadpool_14',['ThreadPool',['../classThreadPool.html',1,'']]],
  ['threadpool_2eh_15',['ThreadPool.h',['../ThreadPool_8h.html',1,'']]],
  ['timer_16',['timer',['../classTimer.html',1,'Timer'],['../classTimer.html#adfe45eea7ac3b53db9be63ad0e7a1aee',1,'Timer::Timer()']]],
  ['to_20add_20a_20custom_20resource_17',['1. How to add a custom resource',['../usage.html#autotoc_md108',1,'']]],
  ['to_20add_20a_20new_20property_18',['5. How to add a new Property',['../usage.html#autotoc_md120',1,'']]],
  ['to_20add_20init_20configs_19',['3. How to add init configs',['../usage.html#autotoc_md114',1,'']]],
  ['to_20create_20a_20resource_20opcode_20rescode_20and_20signal_20opcode_20sigcode_20',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md122',1,'']]],
  ['to_20enforce_20cpu_20architecture_20details_21',['4. How to enforce CPU architecture details',['../usage.html#autotoc_md117',1,'']]],
  ['to_20get_20the_20value_20of_20restype_20for_20a_20resource_22',['List Of Resource Types (Use this table to get the value of ResType for a Resource)',['../index.html#autotoc_md65',1,'']]],
  ['to_20override_20the_20resource_20tune_20and_20untune_20functionalities_23',['2. How to override the Resource tune and untune functionalities.',['../usage.html#autotoc_md112',1,'']]],
  ['to_20physical_20mapping_24',['7. Dynamic Mapper: Logical to Physical Mapping',['../index.html#autotoc_md94',1,'']]],
  ['tune_20and_20untune_20functionalities_25',['2. How to override the Resource tune and untune functionalities.',['../usage.html#autotoc_md112',1,'']]],
  ['tune_20request_26',['1. Send a Tune Request',['../index.html#autotoc_md102',1,'']]],
  ['tune_20requests_20formulation_20guide_27',['&quot;Tune&quot; Requests Formulation Guide',['../requests_formulation.html',1,'']]],
  ['tuner_20apis_28',['tuner apis',['../index.html#autotoc_md67',1,'Example Usage of Resource Tuner APIs'],['../index.html#autotoc_md12',1,'Resource Tuner APIs']]],
  ['tuner_20features_29',['Resource Tuner Features',['../index.html#autotoc_md84',1,'']]],
  ['tuner_20key_20points_30',['Resource-tuner Key Points',['../index.html#autotoc_md10',1,'']]],
  ['tuner_3a_20a_20system_20resource_20provisioning_20framework_31',['Resource Tuner: A System Resource Provisioning Framework',['../index.html',1,'']]],
  ['tuneresources_32',['tuneresources',['../index.html#autotoc_md68',1,'tuneResources'],['../group__RESOURCE__TUNER__CLIENT__APIS.html#ga1eac546e5691c0c3d5d7036a68ba6a2b',1,'tuneResources():&#160;ResourceTunerAPIs.h'],['../index.html#autotoc_md13',1,'tuneResources']]],
  ['tunesignal_33',['tunesignal',['../group__RESOURCE__TUNER__CLIENT__APIS.html#ga946223b16775999ff6c088c3623175c2',1,'tuneSignal():&#160;ResourceTunerAPIs.h'],['../index.html#autotoc_md21',1,'tuneSignal']]],
  ['two_20resources_34',['Sample Resource config file with two resources.',['../usage.html#autotoc_md109',1,'']]],
  ['types_20use_20this_20table_20to_20get_20the_20value_20of_20restype_20for_20a_20resource_35',['List Of Resource Types (Use this table to get the value of ResType for a Resource)',['../index.html#autotoc_md65',1,'']]]
];
