var searchData=
[
  ['rate_20limiter_0',['Rate Limiter',['../group__RATE__LIMITER.html',1,'']]],
  ['rate_20limiter_3a_20preventing_20system_20abuse_1',['5. Rate Limiter: Preventing System Abuse',['../index.html#autotoc_md92',1,'']]],
  ['ratelimiter_2',['RateLimiter',['../classRateLimiter.html',1,'']]],
  ['ratelimiter_2eh_3',['RateLimiter.h',['../RateLimiter_8h.html',1,'']]],
  ['readtargetinfo_4',['readTargetInfo',['../classTargetRegistry.html#a3f2d96aefc2104ff5761602b20f5a8a4',1,'TargetRegistry']]],
  ['recovery_5',['9. Crash Recovery',['../index.html#autotoc_md96',1,'']]],
  ['registerresource_6',['registerResource',['../classResourceRegistry.html#a080bc922577ebcb3bcac76b41dfa2a43',1,'ResourceRegistry']]],
  ['registersignal_7',['registerSignal',['../classSignalRegistry.html#ae43082c5f560725e6d505314b25e7e09',1,'SignalRegistry']]],
  ['relay_20and_20teardown_20capabilities_8',['2. Defining feature init, relay and teardown capabilities',['../ext_features.html#autotoc_md130',1,'']]],
  ['relay_20signals_20and_20features_9',['1. Making Use of Relay Signals and Features',['../ext_features.html#autotoc_md128',1,'']]],
  ['relaysignal_10',['relaysignal',['../group__RESOURCE__TUNER__CLIENT__APIS.html#ga1be5e66911b25e8ea64236e8191d29c9',1,'relaySignal():&#160;ResourceTunerAPIs.h'],['../index.html#autotoc_md25',1,'relaySignal']]],
  ['relaytofeature_11',['relayToFeature',['../classExtFeaturesRegistry.html#a4e4331eae9f156bcc983eda62f4bfe74',1,'ExtFeaturesRegistry']]],
  ['removerequest_12',['removerequest',['../classCocoTable.html#a74d26e26627f9b1fff71222543b3b97a',1,'CocoTable::removeRequest()'],['../classRequestManager.html#ab9dd675017b66476e2dfa7ce4389023f',1,'RequestManager::removeRequest()']]],
  ['request_13',['request',['../index.html#autotoc_md102',1,'1. Send a Tune Request'],['../index.html#autotoc_md103',1,'2. Send an Untune Request'],['../index.html#autotoc_md104',1,'3. Send a Retune Request'],['../index.html#autotoc_md105',1,'4. Send a getProp Request'],['../classRequest.html',1,'Request']]],
  ['request_20level_20priorities_14',['3. Request-Level Priorities',['../index.html#autotoc_md90',1,'']]],
  ['request_20processing_15',['Request Processing',['../index.html#autotoc_md86',1,'']]],
  ['requestmanager_16',['RequestManager',['../classRequestManager.html',1,'']]],
  ['requestqueue_17',['RequestQueue',['../classRequestQueue.html',1,'']]],
  ['requestreceiver_18',['RequestReceiver',['../classRequestReceiver.html',1,'']]],
  ['requests_20formulation_20guide_19',['&quot;Tune&quot; Requests Formulation Guide',['../requests_formulation.html',1,'']]],
  ['requesttype_20',['RequestType',['../Utils_8h.html#ae10b07f2d0feb103db7fe4cfd192e5af',1,'Utils.h']]],
  ['required_20modules_21',['Flexible Packaging: Packaging required modules',['../index.html#autotoc_md6',1,'']]],
  ['rescode_22',['Notes on Resource ResCode',['../index.html#autotoc_md64',1,'']]],
  ['rescode_20and_20signal_20opcode_20sigcode_23',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md122',1,'']]],
  ['resconfinfo_24',['ResConfInfo',['../structResConfInfo.html',1,'']]],
  ['resource_25',['resource',['../usage.html#autotoc_md108',1,'1. How to add a custom resource'],['../classResource.html',1,'Resource']]],
  ['resource_20config_20file_20with_20two_20resources_26',['Sample Resource config file with two resources.',['../usage.html#autotoc_md109',1,'']]],
  ['resource_20configs_27',['resource configs',['../index.html#autotoc_md40',1,'2. Resource Configs'],['../index.html#autotoc_md41',1,'Common Resource Configs'],['../index.html#autotoc_md42',1,'Overriding Resource Configs']]],
  ['resource_20format_28',['Resource Format',['../index.html#autotoc_md63',1,'']]],
  ['resource_20indexing_29',['Notes on Resource Indexing',['../usage.html#autotoc_md110',1,'']]],
  ['resource_20level_20policies_30',['2. Resource-Level Policies',['../index.html#autotoc_md89',1,'']]],
  ['resource_20opcode_20rescode_20and_20signal_20opcode_20sigcode_31',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md122',1,'']]],
  ['resource_20rescode_32',['Notes on Resource ResCode',['../index.html#autotoc_md64',1,'']]],
  ['resource_20tune_20and_20untune_20functionalities_33',['2. How to override the Resource tune and untune functionalities.',['../usage.html#autotoc_md112',1,'']]],
  ['resource_20tuner_20apis_34',['resource tuner apis',['../index.html#autotoc_md67',1,'Example Usage of Resource Tuner APIs'],['../index.html#autotoc_md12',1,'Resource Tuner APIs']]],
  ['resource_20tuner_20features_35',['Resource Tuner Features',['../index.html#autotoc_md84',1,'']]],
  ['resource_20tuner_20key_20points_36',['Resource-tuner Key Points',['../index.html#autotoc_md10',1,'']]],
  ['resource_20tuner_3a_20a_20system_20resource_20provisioning_20framework_37',['Resource Tuner: A System Resource Provisioning Framework',['../index.html',1,'']]],
  ['resource_20types_20use_20this_20table_20to_20get_20the_20value_20of_20restype_20for_20a_20resource_38',['List Of Resource Types (Use this table to get the value of ResType for a Resource)',['../index.html#autotoc_md65',1,'']]],
  ['resourceapplytype_39',['ResourceApplyType',['../structResourceApplyType.html',1,'']]],
  ['resourceregistry_40',['ResourceRegistry',['../classResourceRegistry.html',1,'']]],
  ['resources_41',['Sample Resource config file with two resources.',['../usage.html#autotoc_md109',1,'']]],
  ['resourcetunerapis_2eh_42',['ResourceTunerAPIs.h',['../ResourceTunerAPIs_8h.html',1,'']]],
  ['restune_5fregister_5fapplier_5fcb_43',['restune_register_applier_cb',['../index.html#autotoc_md74',1,'RESTUNE_REGISTER_APPLIER_CB'],['../Extensions_8h.html#a07f3a94d2e5423966ab6a4ff2bbe6f4c',1,'RESTUNE_REGISTER_APPLIER_CB:&#160;Extensions.h']]],
  ['restune_5fregister_5fconfig_44',['restune_register_config',['../index.html#autotoc_md80',1,'RESTUNE_REGISTER_CONFIG'],['../Extensions_8h.html#a2a542be341fae3bc89c4aa1df6c7d7ad',1,'RESTUNE_REGISTER_CONFIG:&#160;Extensions.h']]],
  ['restune_5fregister_5ftear_5fcb_45',['restune_register_tear_cb',['../index.html#autotoc_md77',1,'RESTUNE_REGISTER_TEAR_CB'],['../Extensions_8h.html#ad11f4b99357458d1cb7ad79ff741dce5',1,'RESTUNE_REGISTER_TEAR_CB:&#160;Extensions.h']]],
  ['restype_20for_20a_20resource_46',['List Of Resource Types (Use this table to get the value of ResType for a Resource)',['../index.html#autotoc_md65',1,'']]],
  ['retune_20request_47',['3. Send a Retune Request',['../index.html#autotoc_md104',1,'']]],
  ['retuneresources_48',['retuneresources',['../index.html#autotoc_md69',1,'retuneResources'],['../index.html#autotoc_md15',1,'retuneResources'],['../group__RESOURCE__TUNER__CLIENT__APIS.html#ga3e60de0521a903c940e47f2c0a1ced5a',1,'retuneResources():&#160;ResourceTunerAPIs.h']]]
];
