# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

FeatureConfigs:
  - FeatId: 0x00000001
    Name: "FEAT-1"
    LibPath: "/usr/lib/libtesttuner.so"
    Description: "Simple Algorithmic Feature, defined by the BU"
    Subscribers: [0x000dbbca, 0x000a00ff]

  - FeatId: 0x00000002
    Name: "FEAT-2"
    LibPath: "/usr/lib/libpropagate.so"
    Description: "Simple Observer-Observable Feature, defined by the BU"
    Subscribers: [0x80a105ea, 0x800ccca5]
