# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

ResourceConfigs:
  - ResType: "0x03"
    ResID: "0x0000"
    Name: "SCHED_UTIL_CLAMP_MIN"
    Path: "/proc/sys/kernel/sched_util_clamp_min"
    Supported: true
    HighThreshold: 1024
    LowThreshold: 0
    Permissions: "third_party"
    Modes: ["display_on", "doze"]
    Policy: "lower_is_better"
    ApplyType: "global"

  - ResType: "0x03"
    ResID: "0x0001"
    Name: "SCHED_UTIL_CLAMP_MAX"
    Path: "/proc/sys/kernel/sched_util_clamp_max"
    Supported: true
    HighThreshold: 1024
    LowThreshold: 0
    Permissions: third_party
    Modes: ["display_on", "doze"]
    Policy: higher_is_better
    ApplyType: "global"

  - ResType: "0x04"
    ResID: "0x0000"
    Name: "SCALING_MIN_FREQ_GENERIC"
    Path: "/sys/devices/system/cpu/cpufreq/policy%d/scaling_min_freq"
    Supported: true
    HighThreshold: 1939200
    LowThreshold: 1267200
    Permissions: third_party
    Modes: ["display_on", "doze"]
    Policy: lower_is_better
    ApplyType: "cluster"

  - ResType: "0x04"
    ResID: "0x0001"
    Name: "SCALING_MAX_FREQ_GENERIC"
    Path: "/sys/devices/system/cpu/cpufreq/policy%d/scaling_max_freq"
    Supported: true
    HighThreshold: 1939200
    LowThreshold: 1267200
    Permissions: third_party
    Modes: ["display_on", "doze"]
    Policy: higher_is_better
    ApplyType: "cluster"

  - ResType: "0x09"
    ResID: "0x0000"
    Name: "RES_TUNER_CGROUP_MOVE_PID"
    Path: "/sys/fs/cgroup/%s/cgroup.procs"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"
    Policy: instant_apply

  - ResType: "0x09"
    ResID: "0x0001"
    Name: "RES_TUNER_CGROUP_MOVE_TID"
    Path: "/sys/fs/cgroup/%s/cgroup.threads"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"
    Policy: instant_apply

  - ResType: "0x09"
    ResID: "0x0002"
    Name: "RES_TUNER_CGROUP_RUN_ON_CORES"
    Path: "/sys/fs/cgroup/%s/cpuset.cpus"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"
    Policy: instant_apply

  - ResType: "0x09"
    ResID: "0x0003"
    Name: "RES_TUNER_CGROUP_RUN_ON_CORES_EXCLUSIVELY"
    Path: "/sys/fs/cgroup/%s/cpuset.cpus.partition"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"
    Policy: instant_apply

  - ResType: "0x09"
    ResID: "0x0004"
    Name: "RES_TUNER_CGROUP_FREEZE"
    Path: "/sys/fs/cgroup/%s/cgroup.freeze"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"
    Policy: instant_apply

  - ResType: "0x09"
    ResID: "0x0005"
    Name: "RES_TUNER_CGROUP_LIMIT_CPU_TIME"
    Path: "/sys/fs/cgroup/%s/cpu.max"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"
    Policy: higher_is_better

  - ResType: "0x09"
    ResID: "0x0006"
    Name: "RES_TUNER_CGROUP_RUN_WHEN_CPU_IDLE"
    Path: "/sys/fs/cgroup/%s/cpu.idle"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"
    Policy: instant_apply

  - ResType: "0x09"
    ResID: "0x0007"
    Name: "RES_TUNER_CGROUP_UCLAMP_MIN"
    Path: "/sys/fs/cgroup/%s/cpu.uclamp.min"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"
    Policy: lower_is_better

  - ResType: "0x09"
    ResID: "0x0008"
    Name: "RES_TUNER_CGROUP_UCLAMP_MAX"
    Path: "/sys/fs/cgroup/%s/cpu.uclamp.max"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"
    Policy: higher_is_better

  - ResType: "0x09"
    ResID: "0x0009"
    Name: "RES_TUNER_CGROUP_RELATIVE_CPU_WEIGHT"
    Path: "/sys/fs/cgroup/%s/cpu.weight"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"
    Policy: instant_apply

  - ResType: "0x09"
    ResID: "0x000a"
    Name: "RES_TUNER_CGROUP_MAX_MEMORY"
    Path: "/sys/fs/cgroup/%s/memory.max"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"
    Policy: higher_is_better

  - ResType: "0x09"
    ResID: "0x000b"
    Name: "RES_TUNER_CGROUP_MIN_MEMORY"
    Path: "/sys/fs/cgroup/%s/memory.min"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"
    Policy: lower_is_better

  - ResType: "0x09"
    ResID: "0x000c"
    Name: "RES_TUNER_CGROUP_CPU_LATENCY"
    Path: "/sys/fs/cgroup/%s/cpu.latency_nice"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"
    Policy: lower_is_better
