# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

ResourceConfigs:
  - ResType: "0x03"
    ResID: "0x0000"
    Name: "/proc/sys/kernel/sched_util_clamp_min"
    Supported: true
    HighThreshold: 1024
    LowThreshold: 0
    Permissions: "third_party"
    Modes: ["display_on", "doze"]
    Policy: "higher_is_better"
    CoreLevelConflict: false
    ApplyType: "global"

  - ResType: "0x03"
    ResID: "0x0001"
    Name: "/proc/sys/kernel/sched_util_clamp_max"
    Supported: true
    HighThreshold: 1024
    LowThreshold: 0
    Permissions: "third_party"
    Modes: ["display_on", "doze"]
    Policy: "lower_is_better"
    CoreLevelConflict: false
    ApplyType: "global"

  - ResType: "0x04"
    ResID: "0x0000"
    Name: "/sys/devices/system/cpu/cpufreq/policy0/scaling_min_freq"
    Supported: true
    HighThreshold: 1939200
    LowThreshold: 1267200
    Permissions: third_party
    Modes: ["display_on", "display_off"]
    Policy: lower_is_better
    CoreLevelConflict: true
    ApplyType: "global"

  - ResType: "0x04"
    ResID: "0x0001"
    Name: "/sys/devices/system/cpu/cpufreq/policy1/scaling_min_freq"
    Supported: true
    HighThreshold: 1939200
    LowThreshold: 1267200
    Permissions: third_party
    Modes: ["display_on", "display_off"]
    Policy: instant_apply
    CoreLevelConflict: true
    ApplyType: "global"

  - ResType: "0x04"
    ResID: "0x0002"
    Name: "/sys/devices/system/cpu/cpufreq/policy2/scaling_min_freq"
    Supported: true
    HighThreshold: 1939200
    LowThreshold: 1267200
    Permissions: third_party
    Modes: ["display_on", "display_off"]
    Policy: lazy_apply
    CoreLevelConflict: false
    ApplyType: "global"

  - ResType: "0x04"
    ResID: "0x0003"
    Name: "/sys/devices/system/cpu/cpufreq/policy3/scaling_min_freq"
    Supported: true
    HighThreshold: 1939200
    LowThreshold: 1267200
    Permissions: third_party
    Modes: ["display_on", "display_off"]
    Policy: lower_is_better
    CoreLevelConflict: true
    ApplyType: "global"

  - ResType: "0x04"
    ResID: "0x0100"
    Name: "/sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq"
    Supported: true
    HighThreshold: 1939200
    LowThreshold: 1267200
    Permissions: third_party
    Modes: ["display_on", "display_off"]
    Policy: higher_is_better
    CoreLevelConflict: false
    ApplyType: "global"

  - ResType: "0x04"
    ResID: "0x0101"
    Name: "/sys/devices/system/cpu/cpufreq/policy1/scaling_max_freq"
    Supported: true
    HighThreshold: 1939200
    LowThreshold: 1267200
    Permissions: third_party
    Modes: ["display_on", "display_off"]
    Policy: higher_is_better
    CoreLevelConflict: true
    ApplyType: "global"

  - ResType: "0x04"
    ResID: "0x0102"
    Name: "/sys/devices/system/cpu/cpufreq/policy2/scaling_max_freq"
    Supported: true
    HighThreshold: 1939200
    LowThreshold: 1267200
    Permissions: third_party
    Modes: ["display_on", "display_off"]
    Policy: higher_is_better
    CoreLevelConflict: false
    ApplyType: "global"

  - ResType: "0x04"
    ResID: "0x0103"
    Name: "/sys/devices/system/cpu/cpufreq/policy3/scaling_max_freq"
    Supported: true
    HighThreshold: 1939200
    LowThreshold: 1267200
    Permissions: third_party
    Modes: ["display_on", "display_off"]
    Policy: higher_is_better
    CoreLevelConflict: true
    ApplyType: "global"

  - ResType: "0x09"
    ResID: "0x0000"
    Name: "RES_TUNER_CGROUP_MOVE_PROCS"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"

  - ResType: "0x09"
    ResID: "0x0001"
    Name: "RES_TUNER_CGROUP_MOVE_THREADS"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"

  - ResType: "0x09"
    ResID: "0x0002"
    Name: "RES_TUNER_CGROUP_RUN_ON_CORES"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"

  - ResType: "0x09"
    ResID: "0x0003"
    Name: "RES_TUNER_CGROUP_RUN_ON_CORES_EXCLUSIVELY"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"

  - ResType: "0x09"
    ResID: "0x0004"
    Name: "RES_TUNER_CGROUP_FREEZE"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"

  - ResType: "0x09"
    ResID: "0x0005"
    Name: "RES_TUNER_CGROUP_UNFREEZE"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"

  - ResType: "0x09"
    ResID: "0x0006"
    Name: "RES_TUNER_RUN_WHEN_CPU_IDLE"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"

  - ResType: "0x09"
    ResID: "0x0007"
    Name: "RES_TUNER_UCLAMP_MIN"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"

  - ResType: "0x09"
    ResID: "0x0008"
    Name: "RES_TUNER_UCLAMP_MAX"
    Supported: true
    Permissions: "system"
    ApplyType: "cgroup"
