= urmCli(8)
URM Maintainers (Maintainers.userspace-resource-moderator@qti.qualcomm.com)
:doctype: manpage

== NAME

urmCli - URM (Userspace Resource Manager) Client CLI

== SYNOPSIS

 urmCli [--tune|--untune |--retune|--signal|--getprop]

== DESCRIPTION

urmCli is a client facing command line utility provided by URM to interact with the server.
This is provided primarily to help with quick testing, to see whether the required configurations
are being applied correctly as well as helping with development and debugging.

== OPTIONS

*--tune*::
Issue a tuneResources request for one or more resources for a certain duration

*--untune*::
Untune or teardown a previously issued tune Request.

*--retune*::
Extend the duration of a previously issued tune Request.

*--signal*::
Issue a tuneSignal request for a certain duration

*--getprop*::
Get the value for a certain property from URM's Property Registry.

== EXAMPLES

*Tune Resources Requests*

- urmCli --tune --duration 5000 --priority 0 --num 1 --res "65536:700" (Single Resource in a Request)

- urmCli --tune --duration 4400 --priority 1 --num 2 --res "0x80030000:700,0x80040001:155667" (Multiple Resources in single Request)

- urmCli --tune --duration 9500 --priority 0 --num 1 --res "0x00090002:0,0,1,3,5" (Multi-Valued Resource)

- urmCli --tune --duration 5000 --priority 0 --num 1 --res "0x00040000#0x00000100:1620438" (Specifying ResInfo, useful for Core and Cluster type Resources)

*Untune Requests*

- urmCli --untune --handle 50 (untune request with handle 50)

*Retune Requests*

- urmCli --retune --handle 7 --duration 8000 (Extend the duration of request with handle 7 to 8000 ms)

*Tune Signal Requests*

- urmCli --signal --scode "0x00fe0ab1" (Acquire signal with SigCode: 0x00fe0ab1)

*Fetch Property or getProp Request*

- urmCli --getProp --key "urm.logging.level" (Get the value for the key: "urm.logging.level")

== SEE ALSO

urm(8)
